In [2]:
from pathlib import Path

import polars as pl
import pandas as pd

from IPython.display import display

ROOT = Path.cwd().parent

DATASETS = {
    "trades": ROOT / "data/merged/910004",
    "depth": ROOT / "data/merged/920002",
    "combined": ROOT / "data/merged/920003",
}

for name, path in DATASETS.items():
    print(f"{name:>10} | exists={path.exists()} | {path}")

    trades | exists=True | /home/pasha/projects/bybit-history-downloader/data/merged/910004
     depth | exists=True | /home/pasha/projects/bybit-history-downloader/data/merged/920002
  combined | exists=True | /home/pasha/projects/bybit-history-downloader/data/merged/920003

In [3]:
import json
import pyarrow.parquet as pq

for name, path in DATASETS.items():
    manifest = json.loads((path / "manifest.json").read_text())

    files = sorted(path.rglob("*.parquet"))

    print(f"\n{'=' * 80}")
    print(f"MARKETFORGE — {name.upper()}")
    print(f"{'=' * 80}")

    print(f"Events : {manifest['events_written']:,}")
    print(f"Files  : {len(files)}")

    if files:
        print(f"\nFirst file: {files[0].relative_to(path)}")
        print("\nSchema:")
        print(pq.ParquetFile(files[0]).schema_arrow)

================================================================================
MARKETFORGE — TRADES
================================================================================
Events : 50,106,717
Files  : 16

First file: timeline/partition-000000/part-000000.parquet

Schema:
event_timestamp_ns: int64 not null
stream_rank: uint32 not null
event_kind: uint8 not null
dataset_id: uint64 not null
task_id: uint64 not null
event_ordinal: uint64 not null
canonical_row_offset: uint64 not null
canonical_row_count: uint64 not null
event_boundary: uint8
source_operation: uint8

================================================================================
MARKETFORGE — DEPTH
================================================================================
Events : 405,581,426
Files  : 64

First file: timeline/partition-000000/part-000000.parquet

Schema:
event_timestamp_ns: int64 not null
stream_rank: uint32 not null
dataset_id: uint64 not null
task_id: uint64 not null
event_ordinal: uint64 not null
canonical_row_offset: uint64 not null
canonical_row_count: uint64 not null
event_boundary: uint8 not null
source_operation: uint8 not null

================================================================================
MARKETFORGE — COMBINED
================================================================================
Events : 455,688,143
Files  : 64

First file: timeline/partition-000000/part-000000.parquet

Schema:
event_timestamp_ns: int64 not null
stream_rank: uint32 not null
event_kind: uint8 not null
dataset_id: uint64 not null
task_id: uint64 not null
event_ordinal: uint64 not null
canonical_row_offset: uint64 not null
canonical_row_count: uint64 not null
event_boundary: uint8
source_operation: uint8

In [4]:
trades = pl.scan_parquet(
    str(DATASETS["trades"] / "**/*.parquet"),
    glob=True,
)

display(trades.head(20).collect())

shape: (20, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ event_tim ┆ stream_ra ┆ event_kin ┆ dataset_i ┆ … ┆ canonical ┆ canonical ┆ event_bou ┆ source_o │
│ estamp_ns ┆ nk        ┆ d         ┆ d         ┆   ┆ _row_offs ┆ _row_coun ┆ ndary     ┆ peration │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ et        ┆ t         ┆ ---       ┆ ---      │
│ i64       ┆ u32       ┆ u8        ┆ u64       ┆   ┆ ---       ┆ ---       ┆ u8        ┆ u8       │
│           ┆           ┆           ┆           ┆   ┆ u64       ┆ u64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62633     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62634     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62635     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62636     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62637     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62648     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62649     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62650     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62651     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62652     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
depth = pl.scan_parquet(
    str(DATASETS["depth"] / "**/*.parquet"),
    glob=True,
)

display(depth.head(20).collect())

shape: (20, 9)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ event_time ┆ stream_ra ┆ dataset_i ┆ task_id ┆ … ┆ canonical ┆ canonical ┆ event_bou ┆ source_op │
│ stamp_ns   ┆ nk        ┆ d         ┆ ---     ┆   ┆ _row_offs ┆ _row_coun ┆ ndary     ┆ eration   │
│ ---        ┆ ---       ┆ ---       ┆ u64     ┆   ┆ et        ┆ t         ┆ ---       ┆ ---       │
│ i64        ┆ u32       ┆ u64       ┆         ┆   ┆ ---       ┆ ---       ┆ u8        ┆ u8        │
│            ┆           ┆           ┆         ┆   ┆ u64       ┆ u64       ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 0         ┆ 44061     ┆ 1         ┆ 0         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 44061     ┆ 1         ┆ 0         ┆ 2         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 44062     ┆ 1         ┆ 0         ┆ 2         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 44063     ┆ 1         ┆ 0         ┆ 2         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 44064     ┆ 1         ┆ 0         ┆ 2         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …       ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 44075     ┆ 1         ┆ 0         ┆ 2         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 44076     ┆ 1         ┆ 0         ┆ 2         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 44077     ┆ 1         ┆ 0         ┆ 2         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 44078     ┆ 1         ┆ 0         ┆ 2         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1788220800 ┆ 3         ┆ 96        ┆ 0       ┆ … ┆ 44079     ┆ 1         ┆ 0         ┆ 2         │
│ 000000000  ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
combined = pl.scan_parquet(
    str(DATASETS["combined"] / "**/*.parquet"),
    glob=True,
)

display(combined.head(30).collect())

shape: (30, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ event_tim ┆ stream_ra ┆ event_kin ┆ dataset_i ┆ … ┆ canonical ┆ canonical ┆ event_bou ┆ source_o │
│ estamp_ns ┆ nk        ┆ d         ┆ d         ┆   ┆ _row_offs ┆ _row_coun ┆ ndary     ┆ peration │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ et        ┆ t         ┆ ---       ┆ ---      │
│ i64       ┆ u32       ┆ u8        ┆ u64       ┆   ┆ ---       ┆ ---       ┆ u8        ┆ u8       │
│           ┆           ┆           ┆           ┆   ┆ u64       ┆ u64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62633     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62634     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62635     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62636     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62637     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 178822080 ┆ 12        ┆ 0         ┆ 109       ┆ … ┆ 47830     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 12        ┆ 0         ┆ 109       ┆ … ┆ 47831     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 12        ┆ 0         ┆ 109       ┆ … ┆ 47832     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 12        ┆ 0         ┆ 109       ┆ … ┆ 47833     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 12        ┆ 0         ┆ 109       ┆ … ┆ 47834     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
preview = (
    combined
    .head(100)
    .with_columns(
        pl.from_epoch(
            pl.col("event_timestamp_ns"),
            time_unit="ns",
        ).alias("datetime_utc")
    )
    .collect()
)

display(preview)

shape: (100, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ event_tim ┆ stream_ra ┆ event_kin ┆ dataset_i ┆ … ┆ canonical ┆ event_bou ┆ source_op ┆ datetime │
│ estamp_ns ┆ nk        ┆ d         ┆ d         ┆   ┆ _row_coun ┆ ndary     ┆ eration   ┆ _utc     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ t         ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ u32       ┆ u8        ┆ u64       ┆   ┆ ---       ┆ u8        ┆ u8        ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ u64       ┆           ┆           ┆ [ns]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 1         ┆ null      ┆ null      ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 1         ┆ null      ┆ null      ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 1         ┆ null      ┆ null      ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 1         ┆ null      ┆ null      ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 1         ┆ null      ┆ null      ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 178822080 ┆ 24        ┆ 1         ┆ 96        ┆ … ┆ 1         ┆ 0         ┆ 2         ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ 178822080 ┆ 24        ┆ 1         ┆ 96        ┆ … ┆ 1         ┆ 0         ┆ 2         ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ 178822080 ┆ 24        ┆ 1         ┆ 96        ┆ … ┆ 1         ┆ 0         ┆ 2         ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ 178822080 ┆ 24        ┆ 1         ┆ 96        ┆ … ┆ 1         ┆ 0         ┆ 2         ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ 178822080 ┆ 24        ┆ 1         ┆ 96        ┆ … ┆ 1         ┆ 0         ┆ 2         ┆ 2026-09- │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
distribution = (
    combined
    .group_by("event_kind")
    .agg(pl.len().alias("events"))
    .collect()
    .sort("event_kind")
)

display(distribution)

shape: (2, 2)
┌────────────┬───────────┐
│ event_kind ┆ events    │
│ ---        ┆ ---       │
│ u8         ┆ u32       │
╞════════════╪═══════════╡
│ 0          ┆ 50106717  │
│ 1          ┆ 405581426 │
└────────────┴───────────┘

In [9]:
import json
from pathlib import Path

jobs_dir = ROOT / "data/.jobs/process"

metadata = []

for path in jobs_dir.glob("*.json"):
    job = json.loads(path.read_text())

    if not job.get("tasks"):
        continue

    task = job["tasks"][0]

    metadata.append({
        "dataset_id": job["dataset_id"],
        "exchange": task["exchange"],
        "symbol": task["symbol"],
        "stream_id": task["stream_id"],
        "content_type": job["output"]["content_type"],
    })

metadata = pl.DataFrame(metadata).unique(subset=["dataset_id"])

display(metadata.sort("dataset_id"))

shape: (37, 5)
┌────────────┬──────────┬───────────────────┬─────────────────────────────────┬──────────────┐
│ dataset_id ┆ exchange ┆ symbol            ┆ stream_id                       ┆ content_type │
│ ---        ┆ ---      ┆ ---               ┆ ---                             ┆ ---          │
│ i64        ┆ str      ┆ str               ┆ str                             ┆ str          │
╞════════════╪══════════╪═══════════════════╪═════════════════════════════════╪══════════════╡
│ 88         ┆ bybit    ┆ BTCUSDT           ┆ bybit:perpetual:linear:BTCUSDT… ┆ trades       │
│ 89         ┆ bybit    ┆ BTCUSDT           ┆ bybit:perpetual:linear:BTCUSDT… ┆ depth        │
│ 90         ┆ binance  ┆ BTCUSDT           ┆ binance:perpetual:linear:BTCUS… ┆ trades       │
│ 91         ┆ okx      ┆ BTC-USDT-SWAP     ┆ okx:perpetual:linear:BTC-USDT-… ┆ trades       │
│ 92         ┆ okx      ┆ BTC-USDT-SWAP     ┆ okx:perpetual:linear:BTC-USDT-… ┆ depth        │
│ …          ┆ …        ┆ …                 ┆ …                               ┆ …            │
│ 120        ┆ okx      ┆ BTC-USD_UM-261225 ┆ okx:future:linear:BTC-USD_UM-2… ┆ trades       │
│ 121        ┆ okx      ┆ BTC-USD_UM-261225 ┆ okx:future:linear:BTC-USD_UM-2… ┆ depth        │
│ 122        ┆ okx      ┆ BTC-USD-261225    ┆ okx:future:inverse:BTC-USD-261… ┆ trades       │
│ 123        ┆ okx      ┆ BTC-USD-261225    ┆ okx:future:inverse:BTC-USD-261… ┆ depth        │
│ 900001     ┆ gateio   ┆ BTC_USDT          ┆ gateio:spot:spot:BTC_USDT:l2    ┆ depth        │
└────────────┴──────────┴───────────────────┴─────────────────────────────────┴──────────────┘

In [10]:
timeline = (
    combined
    .head(1000)
    .join(metadata.lazy(), on="dataset_id", how="left")
    .with_columns(
        pl.from_epoch(
            pl.col("event_timestamp_ns"),
            time_unit="ns",
        ).alias("datetime_utc"),

        pl.when(pl.col("event_kind") == 0)
        .then(pl.lit("TRADE"))
        .otherwise(pl.lit("DEPTH"))
        .alias("event_type"),
    )
    .select(
        "datetime_utc",
        "exchange",
        "symbol",
        "event_type",
        "dataset_id",
        "task_id",
        "event_ordinal",
        "canonical_row_offset",
        "canonical_row_count",
    )
    .collect()
)

display(timeline.head(50))

shape: (50, 9)
┌────────────┬──────────┬─────────┬────────────┬───┬─────────┬────────────┬────────────┬───────────┐
│ datetime_u ┆ exchange ┆ symbol  ┆ event_type ┆ … ┆ task_id ┆ event_ordi ┆ canonical_ ┆ canonical │
│ tc         ┆ ---      ┆ ---     ┆ ---        ┆   ┆ ---     ┆ nal        ┆ row_offset ┆ _row_coun │
│ ---        ┆ str      ┆ str     ┆ str        ┆   ┆ u64     ┆ ---        ┆ ---        ┆ t         │
│ datetime[n ┆          ┆         ┆            ┆   ┆         ┆ u64        ┆ u64        ┆ ---       │
│ s]         ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆ u64       │
╞════════════╪══════════╪═════════╪════════════╪═══╪═════════╪════════════╪════════════╪═══════════╡
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 2       ┆ 62633      ┆ 62633      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 2       ┆ 62634      ┆ 62634      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 2       ┆ 62635      ┆ 62635      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 2       ┆ 62636      ┆ 62636      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 2       ┆ 62637      ┆ 62637      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
│ …          ┆ …        ┆ …       ┆ …          ┆ … ┆ …       ┆ …          ┆ …          ┆ …         │
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 0       ┆ 47850      ┆ 47850      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 0       ┆ 47851      ┆ 47851      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 0       ┆ 47852      ┆ 47852      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 0       ┆ 47853      ┆ 47853      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
│ 2026-09-01 ┆ bitget   ┆ BTCUSDT ┆ TRADE      ┆ … ┆ 0       ┆ 47854      ┆ 47854      ┆ 1         │
│ 00:00:00   ┆          ┆         ┆            ┆   ┆         ┆            ┆            ┆           │
└────────────┴──────────┴─────────┴────────────┴───┴─────────┴────────────┴────────────┴───────────┘

In [12]:
import json
from pathlib import Path

dataset_id = 93

# Locate the actual canonical dataset using its manifest.
matches = []

for path in (ROOT / "data").rglob("manifest.json"):
    if "merged" in path.parts:
        continue

    try:
        manifest = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        continue

    if manifest.get("dataset_id") == dataset_id:
        matches.append(path.parent)

assert len(matches) == 1, (
    f"Expected one dataset {dataset_id}, found: {matches}"
)

dataset_path = matches[0]
manifest = json.loads((dataset_path / "manifest.json").read_text())

print("DATASET:", dataset_id)
print("PATH:", dataset_path)

print("\nCANONICAL FILES:")

for entry in manifest["files"][:10]:
    print(entry["path"], "| rows:", entry.get("rows"))

DATASET: 93
PATH: /home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/bitget-perpetual-linear-BTCUSDT-trade-20260901-20260904-d93

CANONICAL FILES:
tasks/task-000000/trades/part-000000.parquet | rows: 100000
tasks/task-000001/trades/part-000000.parquet | rows: 100000
tasks/task-000002/trades/part-000000.parquet | rows: 100000
tasks/task-000003/trades/part-000000.parquet | rows: 100000
tasks/task-000004/trades/part-000000.parquet | rows: 100000
tasks/task-000005/trades/part-000000.parquet | rows: 100000
tasks/task-000006/trades/part-000000.parquet | rows: 100000
tasks/task-000007/trades/part-000000.parquet | rows: 100000
tasks/task-000008/trades/part-000000.parquet | rows: 100000
tasks/task-000009/trades/part-000000.parquet | rows: 83742

In [15]:
import pyarrow.parquet as pq
import pyarrow.compute as pc
import pyarrow as pa
import polars as pl

from IPython.display import display

# Read only 30 rows from the first canonical trade file.
parquet = pq.ParquetFile(trade_files[0])

batch = next(parquet.iter_batches(batch_size=30))
table = pa.Table.from_batches([batch])

# Convert Decimal256 columns to Float64 for visualization.
columns = []

for field in table.schema:
    column = table[field.name]

    if pa.types.is_decimal256(field.type):
        column = pc.cast(column, pa.float64())

    columns.append(column)

table = pa.table(
    {
        field.name: column
        for field, column in zip(table.schema, columns)
    }
)

trades_preview = pl.from_arrow(table)

display(trades_preview)

shape: (30, 18)
┌────────────┬────────────┬──────────┬────────────┬───┬──────────┬─────────┬───────────┬───────────┐
│ event_time ┆ system_tim ┆ exchange ┆ instrument ┆ … ┆ trade_iv ┆ mark_iv ┆ index_pri ┆ mark_pric │
│ stamp_ns   ┆ estamp_ns  ┆ ---      ┆ _id        ┆   ┆ ---      ┆ ---     ┆ ce        ┆ e         │
│ ---        ┆ ---        ┆ str      ┆ ---        ┆   ┆ f64      ┆ f64     ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆          ┆ i64        ┆   ┆          ┆         ┆ f64       ┆ f64       │
╞════════════╪════════════╪══════════╪════════════╪═══╪══════════╪═════════╪═══════════╪═══════════╡
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
│ …          ┆ …          ┆ …        ┆ …          ┆ … ┆ …        ┆ …       ┆ …         ┆ …         │
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
│ 1788192000 ┆ null       ┆ bitget   ┆ 14215      ┆ … ┆ null     ┆ null    ┆ null      ┆ null      │
│ 000000000  ┆            ┆          ┆            ┆   ┆          ┆         ┆           ┆           │
└────────────┴────────────┴──────────┴────────────┴───┴──────────┴─────────┴───────────┴───────────┘

In [16]:
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.compute as pc
import polars as pl

from IPython.display import display

depth_path = ROOT / "data/processed/96"

depth_files = sorted(
    depth_path.glob("tasks/task-*/depth/part-*.parquet")
)

assert depth_files, "No canonical depth files found"

print("MARKETFORGE — CANONICAL DEPTH")
print("=" * 80)
print("Files:", len(depth_files))
print("\nSchema:")
print(pq.ParquetFile(depth_files[0]).schema_arrow)

parquet = pq.ParquetFile(depth_files[0])
batch = next(parquet.iter_batches(batch_size=30))

table = pa.Table.from_batches([batch])

# Decimal256 -> Float64 for visualization only
table = pa.table({
    field.name: (
        pc.cast(table[field.name], pa.float64())
        if pa.types.is_decimal256(field.type)
        else table[field.name]
    )
    for field in table.schema
})

depth_preview = pl.from_arrow(table)

display(depth_preview)

MARKETFORGE — CANONICAL DEPTH
================================================================================
Files: 173

Schema:
event_timestamp_ns: int64 not null
system_timestamp_ns: int64
exchange: string not null
instrument_id: int64 not null
symbol: string not null
stream_id: string not null
side: string not null
price: decimal256(76, 28) not null
quantity_base: decimal256(76, 28)
quantity_quote: decimal256(76, 28)
quantity_contracts: decimal256(76, 28)
order_count: uint64

shape: (30, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ event_tim ┆ system_ti ┆ exchange ┆ instrumen ┆ … ┆ quantity_ ┆ quantity_ ┆ quantity_ ┆ order_cou │
│ estamp_ns ┆ mestamp_n ┆ ---      ┆ t_id      ┆   ┆ base      ┆ quote     ┆ contracts ┆ nt        │
│ ---       ┆ s         ┆ str      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆ ---       ┆          ┆ i64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ u64       │
│           ┆ i64       ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 375.9051  ┆ 37.59051  ┆ 3.759051e ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆ 6         ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 13.4226   ┆ 2.68452   ┆ 134226.0  ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 16.1094   ┆ 4.83282   ┆ 161094.0  ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 1.0697    ┆ 0.42788   ┆ 10697.0   ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 413.8663  ┆ 206.93315 ┆ 4.138663e ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆ 6         ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 0.0005    ┆ 0.0027    ┆ 5.0       ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 0.0011    ┆ 0.00649   ┆ 11.0      ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 0.0035    ┆ 0.021     ┆ 35.0      ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 0.0005    ┆ 0.00315   ┆ 5.0       ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 178822080 ┆ null      ┆ gateio   ┆ 17397     ┆ … ┆ 2.3       ┆ 16.1      ┆ 23000.0   ┆ null      │
│ 000000000 ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
depth_view = depth_preview

if "event_timestamp_ns" in depth_view.columns:
    depth_view = depth_view.with_columns(
        pl.from_epoch(
            "event_timestamp_ns",
            time_unit="ns",
        ).alias("datetime_utc")
    )

preferred = [
    "datetime_utc",
    "exchange",
    "symbol",
    "side",
    "price",
    "quantity",
    "quantity_base",
    "operation",
    "sequence",
]

display(
    depth_view.select(
        [col for col in preferred if col in depth_view.columns]
    )
)

shape: (30, 6)
┌─────────────────────┬──────────┬──────────┬──────┬───────┬───────────────┐
│ datetime_utc        ┆ exchange ┆ symbol   ┆ side ┆ price ┆ quantity_base │
│ ---                 ┆ ---      ┆ ---      ┆ ---  ┆ ---   ┆ ---           │
│ datetime[ns]        ┆ str      ┆ str      ┆ str  ┆ f64   ┆ f64           │
╞═════════════════════╪══════════╪══════════╪══════╪═══════╪═══════════════╡
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 0.1   ┆ 375.9051      │
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 0.2   ┆ 13.4226       │
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 0.3   ┆ 16.1094       │
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 0.4   ┆ 1.0697        │
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 0.5   ┆ 413.8663      │
│ …                   ┆ …        ┆ …        ┆ …    ┆ …     ┆ …             │
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 5.4   ┆ 0.0005        │
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 5.9   ┆ 0.0011        │
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 6.0   ┆ 0.0035        │
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 6.3   ┆ 0.0005        │
│ 2026-09-01 00:00:00 ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 7.0   ┆ 2.3           │
└─────────────────────┴──────────┴──────────┴──────┴───────┴───────────────┘

In [18]:
def prepare_market_view(df, event_type):
    columns = df.columns

    timestamp = (
        "event_timestamp_ns"
        if "event_timestamp_ns" in columns
        else None
    )

    if timestamp is None:
        raise ValueError(f"No event timestamp in {event_type} schema")

    price = "price" if "price" in columns else None

    quantity = next(
        (
            name
            for name in ["quantity_base", "quantity", "size"]
            if name in columns
        ),
        None,
    )

    return (
        df
        .with_columns(
            pl.lit(event_type).alias("event_type"),
            pl.from_epoch(
                timestamp,
                time_unit="ns",
            ).alias("datetime_utc"),
        )
        .select(
            "datetime_utc",
            "event_timestamp_ns",
            "event_type",
            *[
                name
                for name in [
                    "exchange",
                    "symbol",
                    "side",
                ]
                if name in columns
            ],
            (
                pl.col(price).alias("price")
                if price
                else pl.lit(None).alias("price")
            ),
            (
                pl.col(quantity).alias("quantity")
                if quantity
                else pl.lit(None).alias("quantity")
            ),
        )
    )


trade_view = prepare_market_view(
    trades_preview,
    "TRADE",
)

book_view = prepare_market_view(
    depth_preview,
    "DEPTH",
)

market_activity = (
    pl.concat(
        [trade_view, book_view],
        how="diagonal_relaxed",
    )
    .sort("event_timestamp_ns", "event_type")
)

display(market_activity)

shape: (60, 8)
┌──────────────┬────────────────────┬────────────┬──────────┬──────────┬──────┬─────────┬──────────┐
│ datetime_utc ┆ event_timestamp_ns ┆ event_type ┆ exchange ┆ symbol   ┆ side ┆ price   ┆ quantity │
│ ---          ┆ ---                ┆ ---        ┆ ---      ┆ ---      ┆ ---  ┆ ---     ┆ ---      │
│ datetime[ns] ┆ i64                ┆ str        ┆ str      ┆ str      ┆ str  ┆ f64     ┆ f64      │
╞══════════════╪════════════════════╪════════════╪══════════╪══════════╪══════╪═════════╪══════════╡
│ 2026-08-31   ┆ 178819200000000000 ┆ TRADE      ┆ bitget   ┆ BTCUSDT  ┆ buy  ┆ 78546.0 ┆ 0.0001   │
│ 16:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
│ 2026-08-31   ┆ 178819200000000000 ┆ TRADE      ┆ bitget   ┆ BTCUSDT  ┆ buy  ┆ 78546.0 ┆ 0.0001   │
│ 16:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
│ 2026-08-31   ┆ 178819200000000000 ┆ TRADE      ┆ bitget   ┆ BTCUSDT  ┆ buy  ┆ 78546.0 ┆ 0.0001   │
│ 16:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
│ 2026-08-31   ┆ 178819200000000000 ┆ TRADE      ┆ bitget   ┆ BTCUSDT  ┆ buy  ┆ 78546.0 ┆ 0.0001   │
│ 16:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
│ 2026-08-31   ┆ 178819200000000000 ┆ TRADE      ┆ bitget   ┆ BTCUSDT  ┆ buy  ┆ 78546.0 ┆ 0.0001   │
│ 16:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
│ …            ┆ …                  ┆ …          ┆ …        ┆ …        ┆ …    ┆ …       ┆ …        │
│ 2026-09-01   ┆ 178822080000000000 ┆ DEPTH      ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 5.4     ┆ 0.0005   │
│ 00:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
│ 2026-09-01   ┆ 178822080000000000 ┆ DEPTH      ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 5.9     ┆ 0.0011   │
│ 00:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
│ 2026-09-01   ┆ 178822080000000000 ┆ DEPTH      ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 6.0     ┆ 0.0035   │
│ 00:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
│ 2026-09-01   ┆ 178822080000000000 ┆ DEPTH      ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 6.3     ┆ 0.0005   │
│ 00:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
│ 2026-09-01   ┆ 178822080000000000 ┆ DEPTH      ┆ gateio   ┆ BTC_USDT ┆ bid  ┆ 7.0     ┆ 2.3      │
│ 00:00:00     ┆ 0                  ┆            ┆          ┆          ┆      ┆         ┆          │
└──────────────┴────────────────────┴────────────┴──────────┴──────────┴──────┴─────────┴──────────┘

In [19]:
import polars as pl
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.compute as pc

from pathlib import Path
from IPython.display import display

ROOT = next(
    p for p in [Path.cwd(), *Path.cwd().parents]
    if (p / "engine/Cargo.toml").exists()
)

MERGED = ROOT / "data/merged/920003"

# Read the merged timeline, not canonical data.
timeline_files = sorted(MERGED.rglob("*.parquet"))

print("Merged Parquet files:", len(timeline_files))

timeline = pl.scan_parquet(
    [str(p) for p in timeline_files]
)

# Take a bounded sample from the actual merged timeline.
sample = timeline.head(1000).collect()

print("Event distribution:")
display(sample.group_by("event_kind").len())

display(sample.head(20))

Merged Parquet files: 64
Event distribution:

shape: (2, 2)
┌────────────┬─────┐
│ event_kind ┆ len │
│ ---        ┆ --- │
│ u8         ┆ u32 │
╞════════════╪═════╡
│ 0          ┆ 337 │
│ 1          ┆ 663 │
└────────────┴─────┘

shape: (20, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ event_tim ┆ stream_ra ┆ event_kin ┆ dataset_i ┆ … ┆ canonical ┆ canonical ┆ event_bou ┆ source_o │
│ estamp_ns ┆ nk        ┆ d         ┆ d         ┆   ┆ _row_offs ┆ _row_coun ┆ ndary     ┆ peration │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ et        ┆ t         ┆ ---       ┆ ---      │
│ i64       ┆ u32       ┆ u8        ┆ u64       ┆   ┆ ---       ┆ ---       ┆ u8        ┆ u8       │
│           ┆           ┆           ┆           ┆   ┆ u64       ┆ u64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62633     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62634     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62635     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62636     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62637     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62648     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62649     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62650     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62651     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 178822080 ┆ 3         ┆ 0         ┆ 93        ┆ … ┆ 62652     ┆ 1         ┆ null      ┆ null     │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
import json

dataset_paths = {}

for manifest_path in (ROOT / "data").rglob("manifest.json"):
    if "merged" in manifest_path.parts:
        continue

    try:
        manifest = json.loads(manifest_path.read_text())
    except (OSError, json.JSONDecodeError):
        continue

    dataset_id = manifest.get("dataset_id")

    if dataset_id is None:
        continue

    dataset_paths.setdefault(dataset_id, []).append(
        manifest_path.parent
    )

# Resolve only datasets referenced by our sample.
required_ids = sample["dataset_id"].unique().to_list()

for dataset_id in required_ids:
    matches = dataset_paths.get(dataset_id, [])

    if len(matches) != 1:
        raise RuntimeError(
            f"Dataset {dataset_id}: expected one location, found {matches}"
        )

print(f"Resolved {len(required_ids)} canonical datasets")

Resolved 19 canonical datasets

In [21]:
from functools import lru_cache

@lru_cache(maxsize=128)
def task_file_inventory(dataset_id, task_id, event_kind):
    dataset_path = dataset_paths[dataset_id][0]

    manifest = json.loads(
        (dataset_path / "manifest.json").read_text()
    )

    kind = "trades" if event_kind == 0 else "depth"

    prefix = f"tasks/task-{task_id:06d}/{kind}/"

    files = [
        entry
        for entry in manifest["files"]
        if entry["path"].startswith(prefix)
        and entry["path"].endswith(".parquet")
    ]

    files.sort(key=lambda entry: entry["path"])

    inventory = []
    offset = 0

    for entry in files:
        rows = entry["rows"]

        inventory.append({
            "path": dataset_path / entry["path"],
            "start": offset,
            "end": offset + rows,
        })

        offset += rows

    return inventory


def read_canonical_rows(
    dataset_id,
    task_id,
    event_kind,
    row_offset,
    row_count,
):
    if row_count == 0:
        return pa.table({})

    inventory = task_file_inventory(
        dataset_id,
        task_id,
        event_kind,
    )

    requested_start = row_offset
    requested_end = row_offset + row_count

    batches = []

    for entry in inventory:
        overlap_start = max(requested_start, entry["start"])
        overlap_end = min(requested_end, entry["end"])

        if overlap_start >= overlap_end:
            continue

        local_start = overlap_start - entry["start"]
        local_count = overlap_end - overlap_start

        parquet = pq.ParquetFile(entry["path"])

        # Read the relevant row groups.
        row_position = 0

        for row_group in range(parquet.num_row_groups):
            metadata = parquet.metadata.row_group(row_group)
            group_rows = metadata.num_rows

            group_start = row_position
            group_end = row_position + group_rows

            row_position = group_end

            if group_end <= local_start:
                continue

            if group_start >= local_start + local_count:
                break

            table = parquet.read_row_group(row_group)

            slice_start = max(local_start - group_start, 0)
            slice_end = min(
                local_start + local_count - group_start,
                group_rows,
            )

            batches.append(
                table.slice(
                    slice_start,
                    slice_end - slice_start,
                )
            )

    if not batches:
        raise RuntimeError(
            f"Canonical rows not found: "
            f"dataset={dataset_id}, task={task_id}, "
            f"offset={row_offset}, count={row_count}"
        )

    return pa.concat_tables(batches)

In [22]:
def arrow_to_polars(table):
    if table.num_rows == 0:
        return None

    columns = {}

    for field in table.schema:
        column = table[field.name]

        if pa.types.is_decimal256(field.type):
            column = pc.cast(column, pa.float64())

        columns[field.name] = column

    return pl.from_arrow(pa.table(columns))

In [23]:
trade_refs = (
    sample
    .filter(pl.col("event_kind") == 0)
    .head(10)
)

resolved_trades = []

for ref in trade_refs.iter_rows(named=True):
    table = read_canonical_rows(
        dataset_id=ref["dataset_id"],
        task_id=ref["task_id"],
        event_kind=0,
        row_offset=ref["canonical_row_offset"],
        row_count=ref["canonical_row_count"],
    )

    frame = arrow_to_polars(table)

    if frame is None:
        continue

    frame = frame.with_columns(
        pl.lit(ref["dataset_id"]).alias("dataset_id"),
        pl.lit(ref["task_id"]).alias("task_id"),
        pl.lit(ref["event_ordinal"]).alias("event_ordinal"),
    )

    resolved_trades.append(frame)

trades_real = pl.concat(
    resolved_trades,
    how="diagonal_relaxed",
)

display(
    trades_real
    .with_columns(
        pl.from_epoch(
            "event_timestamp_ns",
            time_unit="ns",
        ).alias("datetime_utc")
    )
    .select(
        "datetime_utc",
        "exchange",
        "symbol",
        "side",
        "price",
        "quantity_base",
        "quantity_quote",
        "trade_id",
        "dataset_id",
        "task_id",
        "event_ordinal",
    )
)

shape: (10, 11)
┌──────────────┬──────────┬─────────┬──────┬───┬──────────────┬────────────┬─────────┬─────────────┐
│ datetime_utc ┆ exchange ┆ symbol  ┆ side ┆ … ┆ trade_id     ┆ dataset_id ┆ task_id ┆ event_ordin │
│ ---          ┆ ---      ┆ ---     ┆ ---  ┆   ┆ ---          ┆ ---        ┆ ---     ┆ al          │
│ datetime[ns] ┆ str      ┆ str     ┆ str  ┆   ┆ str          ┆ i32        ┆ i32     ┆ ---         │
│              ┆          ┆         ┆      ┆   ┆              ┆            ┆         ┆ i32         │
╞══════════════╪══════════╪═════════╪══════╪═══╪══════════════╪════════════╪═════════╪═════════════╡
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068489 ┆ 93         ┆ 2       ┆ 62633       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 7984512      ┆            ┆         ┆             │
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068489 ┆ 93         ┆ 2       ┆ 62634       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 7984514      ┆            ┆         ┆             │
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068520 ┆ 93         ┆ 2       ┆ 62635       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 8363008      ┆            ┆         ┆             │
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068522 ┆ 93         ┆ 2       ┆ 62636       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 0945920      ┆            ┆         ┆             │
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068522 ┆ 93         ┆ 2       ┆ 62637       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 0945922      ┆            ┆         ┆             │
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068522 ┆ 93         ┆ 2       ┆ 62638       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 0945924      ┆            ┆         ┆             │
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068643 ┆ 93         ┆ 2       ┆ 62639       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 7294080      ┆            ┆         ┆             │
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068643 ┆ 93         ┆ 2       ┆ 62640       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 7294082      ┆            ┆         ┆             │
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068643 ┆ 93         ┆ 2       ┆ 62641       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 7294084      ┆            ┆         ┆             │
│ 2026-09-01   ┆ bitget   ┆ BTCUSDT ┆ sell ┆ … ┆ 147847068643 ┆ 93         ┆ 2       ┆ 62642       │
│ 00:00:00     ┆          ┆         ┆      ┆   ┆ 7294086      ┆            ┆         ┆             │
└──────────────┴──────────┴─────────┴──────┴───┴──────────────┴────────────┴─────────┴─────────────┘

In [24]:
depth_refs = (
    sample
    .filter(
        (pl.col("event_kind") == 1)
        & (pl.col("canonical_row_count") > 0)
        & (pl.col("canonical_row_count") <= 10)
    )
    .head(10)
)

resolved_depth = []

for ref in depth_refs.iter_rows(named=True):
    table = read_canonical_rows(
        dataset_id=ref["dataset_id"],
        task_id=ref["task_id"],
        event_kind=1,
        row_offset=ref["canonical_row_offset"],
        row_count=ref["canonical_row_count"],
    )

    frame = arrow_to_polars(table)

    if frame is None:
        continue

    frame = frame.with_columns(
        pl.lit(ref["dataset_id"]).alias("dataset_id"),
        pl.lit(ref["task_id"]).alias("task_id"),
        pl.lit(ref["event_ordinal"]).alias("event_ordinal"),
    )

    resolved_depth.append(frame)

if resolved_depth:
    depth_real = pl.concat(
        resolved_depth,
        how="diagonal_relaxed",
    )

    print("CANONICAL DEPTH SCHEMA")
    print(depth_real.schema)

    display(depth_real.head(30))
else:
    print("No suitable depth updates in the selected sample.")

CANONICAL DEPTH SCHEMA
Schema({'event_timestamp_ns': Int64, 'system_timestamp_ns': Int64, 'exchange': String, 'instrument_id': Int64, 'symbol': String, 'stream_id': String, 'side': String, 'price': Float64, 'quantity_base': Float64, 'quantity_quote': Float64, 'quantity_contracts': Float64, 'order_count': UInt64, 'dataset_id': Int32, 'task_id': Int32, 'event_ordinal': Int32})

shape: (10, 15)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ event_time ┆ system_tim ┆ exchange ┆ instrumen ┆ … ┆ order_cou ┆ dataset_i ┆ task_id ┆ event_ord │
│ stamp_ns   ┆ estamp_ns  ┆ ---      ┆ t_id      ┆   ┆ nt        ┆ d         ┆ ---     ┆ inal      │
│ ---        ┆ ---        ┆ str      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i32     ┆ ---       │
│ i64        ┆ i64        ┆          ┆ i64       ┆   ┆ u64       ┆ i32       ┆         ┆ i32       │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44062     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44063     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44064     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44065     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44066     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44067     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44068     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44069     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44070     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
│ 1788220800 ┆ null       ┆ gateio   ┆ 17397     ┆ … ┆ null      ┆ 96        ┆ 0       ┆ 44071     │
│ 000000000  ┆            ┆          ┆           ┆   ┆           ┆           ┆         ┆           │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [26]:
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.compute as pc
import polars as pl

# Read only the first 20 records
pf = pq.ParquetFile(files[0])
batch = next(pf.iter_batches(batch_size=20))
table = pa.Table.from_batches([batch])

# Convert Decimal256 to Float64 for display only
table_preview = pa.table({
    field.name: (
        pc.cast(table[field.name], pa.float64())
        if pa.types.is_decimal256(field.type)
        else table[field.name]
    )
    for field in table.schema
})

df = pl.from_arrow(table_preview)

with pl.Config(
    tbl_cols=-1,
    tbl_width_chars=240,
    fmt_str_lengths=40,
):
    display(df)

shape: (20, 12)
┌─────────────────────┬─────────────────────┬──────────┬───────────────┬──────────┬─────────────────────────────────────┬──────┬───────┬───────────────┬────────────────┬────────────────────┬─────────────┐
│ event_timestamp_ns  ┆ system_timestamp_ns ┆ exchange ┆ instrument_id ┆ symbol   ┆ stream_id                           ┆ side ┆ price ┆ quantity_base ┆ quantity_quote ┆ quantity_contracts ┆ order_count │
│ ---                 ┆ ---                 ┆ ---      ┆ ---           ┆ ---      ┆ ---                                 ┆ ---  ┆ ---   ┆ ---           ┆ ---            ┆ ---                ┆ ---         │
│ i64                 ┆ i64                 ┆ str      ┆ i64           ┆ str      ┆ str                                 ┆ str  ┆ f64   ┆ f64           ┆ f64            ┆ f64                ┆ u64         │
╞═════════════════════╪═════════════════════╪══════════╪═══════════════╪══════════╪═════════════════════════════════════╪══════╪═══════╪═══════════════╪════════════════╪════════════════════╪═════════════╡
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 0.1   ┆ 375.9051      ┆ 37.59051       ┆ 3.759051e6         ┆ null        │
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 0.2   ┆ 13.4226       ┆ 2.68452        ┆ 134226.0           ┆ null        │
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 0.3   ┆ 16.1094       ┆ 4.83282        ┆ 161094.0           ┆ null        │
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 0.4   ┆ 1.0697        ┆ 0.42788        ┆ 10697.0            ┆ null        │
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 0.5   ┆ 413.8663      ┆ 206.93315      ┆ 4.138663e6         ┆ null        │
│ …                   ┆ …                   ┆ …        ┆ …             ┆ …        ┆ …                                   ┆ …    ┆ …     ┆ …             ┆ …              ┆ …                  ┆ …           │
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 1.8   ┆ 0.1134        ┆ 0.20412        ┆ 1134.0             ┆ null        │
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 2.0   ┆ 2.4159        ┆ 4.8318         ┆ 24159.0            ┆ null        │
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 2.2   ┆ 0.1364        ┆ 0.30008        ┆ 1364.0             ┆ null        │
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 2.4   ┆ 0.1364        ┆ 0.32736        ┆ 1364.0             ┆ null        │
│ 1788220800000000000 ┆ null                ┆ gateio   ┆ 17397         ┆ BTC_USDT ┆ gateio:perpetual:linear:BTC_USDT:l2 ┆ bid  ┆ 2.6   ┆ 0.1364        ┆ 0.35464        ┆ 1364.0             ┆ null        │
└─────────────────────┴─────────────────────┴──────────┴───────────────┴──────────┴─────────────────────────────────────┴──────┴───────┴───────────────┴────────────────┴────────────────────┴─────────────┘

In [27]:
import json
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.compute as pc
import polars as pl

from IPython.display import display

# Find Bybit canonical depth dataset
dataset_id = 89

matches = []

for path in (ROOT / "data").rglob("manifest.json"):
    if "merged" in path.parts:
        continue

    try:
        manifest = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        continue

    if manifest.get("dataset_id") == dataset_id:
        matches.append(path.parent)

assert len(matches) == 1, f"Expected one dataset, found: {matches}"

depth_path = matches[0]

files = sorted(
    depth_path.glob("tasks/task-*/depth/part-*.parquet")
)

assert files, "No depth Parquet files found"

print("DATASET:", dataset_id)
print("PATH:", depth_path)
print("FILES:", len(files))

pf = pq.ParquetFile(files[0])

print("\nARROW SCHEMA:")
print(pf.schema_arrow)

# Read only first 20 rows
batch = next(pf.iter_batches(batch_size=20))
table = pa.Table.from_batches([batch])

# Decimal256 → Float64 for visualization only
preview = pa.table({
    field.name: (
        pc.cast(table[field.name], pa.float64())
        if pa.types.is_decimal256(field.type)
        else table[field.name]
    )
    for field in table.schema
})

df = pl.from_arrow(preview)

with pl.Config(
    tbl_cols=-1,
    tbl_width_chars=240,
    fmt_str_lengths=45,
):
    print("\nFIRST 20 BYBIT DEPTH ROWS:")
    print(df)

DATASET: 89
PATH: /home/pasha/projects/bybit-history-downloader/data/processed/89
FILES: 62

ARROW SCHEMA:
event_timestamp_ns: int64 not null
system_timestamp_ns: int64
exchange: string not null
instrument_id: int64 not null
symbol: string not null
stream_id: string not null
side: string not null
price: decimal256(76, 28) not null
quantity_base: decimal256(76, 28)
quantity_quote: decimal256(76, 28)
quantity_contracts: decimal256(76, 28)
order_count: uint64

FIRST 20 BYBIT DEPTH ROWS:
shape: (20, 12)
┌─────────────────────┬─────────────────────┬──────────┬───────────────┬─────────┬───────────────────────────────────┬──────┬─────────┬───────────────┬────────────────┬────────────────────┬─────────────┐
│ event_timestamp_ns  ┆ system_timestamp_ns ┆ exchange ┆ instrument_id ┆ symbol  ┆ stream_id                         ┆ side ┆ price   ┆ quantity_base ┆ quantity_quote ┆ quantity_contracts ┆ order_count │
│ ---                 ┆ ---                 ┆ ---      ┆ ---           ┆ ---     ┆ ---                               ┆ ---  ┆ ---     ┆ ---           ┆ ---            ┆ ---                ┆ ---         │
│ i64                 ┆ i64                 ┆ str      ┆ i64           ┆ str     ┆ str                               ┆ str  ┆ f64     ┆ f64           ┆ f64            ┆ f64                ┆ u64         │
╞═════════════════════╪═════════════════════╪══════════╪═══════════════╪═════════╪═══════════════════════════════════╪══════╪═════════╪═══════════════╪════════════════╪════════════════════╪═════════════╡
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78507.8 ┆ 0.13          ┆ 10206.014      ┆ null               ┆ null        │
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78507.9 ┆ 0.003         ┆ 235.5237       ┆ null               ┆ null        │
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78508.0 ┆ 0.004         ┆ 314.032        ┆ null               ┆ null        │
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78508.1 ┆ 0.001         ┆ 78.5081        ┆ null               ┆ null        │
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78508.2 ┆ 0.07          ┆ 5495.574       ┆ null               ┆ null        │
│ …                   ┆ …                   ┆ …        ┆ …             ┆ …       ┆ …                                 ┆ …    ┆ …       ┆ …             ┆ …              ┆ …                  ┆ …           │
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78509.5 ┆ 1.34          ┆ 105202.73      ┆ null               ┆ null        │
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78509.7 ┆ 0.126         ┆ 9892.2222      ┆ null               ┆ null        │
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78509.9 ┆ 0.138         ┆ 10834.3662     ┆ null               ┆ null        │
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78510.0 ┆ 1.522         ┆ 119492.22      ┆ null               ┆ null        │
│ 1788220800125000000 ┆ 1788220800129000000 ┆ bybit    ┆ 688           ┆ BTCUSDT ┆ bybit:perpetual:linear:BTCUSDT:l2 ┆ bid  ┆ 78510.1 ┆ 0.007         ┆ 549.5707       ┆ null               ┆ null        │
└─────────────────────┴─────────────────────┴──────────┴───────────────┴─────────┴───────────────────────────────────┴──────┴─────────┴───────────────┴────────────────┴────────────────────┴─────────────┘

In [28]:
from pathlib import Path
import json
import pyarrow.parquet as pq
import polars as pl
from IPython.display import display

ROOT = next(
    p for p in [Path.cwd(), *Path.cwd().parents]
    if (p / "engine/Cargo.toml").exists()
)

MERGED = ROOT / "data/merged/920003"

manifest = json.loads((MERGED / "manifest.json").read_text())

files = sorted(MERGED.glob("timeline/**/*.parquet"))

print("=" * 80)
print("MARKETFORGE — COMBINED LOGICAL MERGE")
print("=" * 80)

print("\nDATASET:", MERGED)
print("PARQUET FILES:", len(files))
print("TOTAL EVENTS:", f"{manifest['events_written']:,}")

print("\nMANIFEST:")
print(json.dumps(manifest, indent=2, default=str))

print("\nARROW SCHEMA:")
print(pq.ParquetFile(files[0]).schema_arrow)

================================================================================
MARKETFORGE — COMBINED LOGICAL MERGE
================================================================================

DATASET: /home/pasha/projects/bybit-history-downloader/data/merged/920003
PARQUET FILES: 64
TOTAL EVENTS: 455,688,143

MANIFEST:
{
  "protocol_version": 2,
  "timeline_schema_version": 1,
  "job_id": 920003,
  "mode": "combined",
  "input_datasets": [
    {
      "dataset_id": 88,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/bybit-perpetual-linear-BTCUSDT-trade-20260901-20260904-d88",
      "manifest_version": 2
    },
    {
      "dataset_id": 90,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/binance-perpetual-linear-BTCUSDT-trade-20260901-20260904-d90",
      "manifest_version": 2
    },
    {
      "dataset_id": 91,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/okx-perpetual-linear-BTC-USDT-SWAP-trade-20260901-20260904-d91",
      "manifest_version": 2
    },
    {
      "dataset_id": 93,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/bitget-perpetual-linear-BTCUSDT-trade-20260901-20260904-d93",
      "manifest_version": 2
    },
    {
      "dataset_id": 95,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/gateio-perpetual-linear-BTC_USDT-trade-20260901-20261001-d95",
      "manifest_version": 2
    },
    {
      "dataset_id": 97,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/bybit-perpetual-inverse-BTCUSD-trade-20260901-20260904-d97",
      "manifest_version": 2
    },
    {
      "dataset_id": 99,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/binance-perpetual-inverse-BTCUSD_PERP-trade-20260901-20260904-d99",
      "manifest_version": 2
    },
    {
      "dataset_id": 100,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/okx-perpetual-inverse-BTC-USD-SWAP-trade-20260901-20260904-d100",
      "manifest_version": 2
    },
    {
      "dataset_id": 102,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/gateio-perpetual-inverse-BTC_USD-trade-20260901-20261001-d102",
      "manifest_version": 2
    },
    {
      "dataset_id": 104,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/bybit-spot-spot-BTCUSDT-trade-20260901-20260904-d104",
      "manifest_version": 2
    },
    {
      "dataset_id": 106,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/binance-spot-spot-BTCUSDT-trade-20260901-20260904-d106",
      "manifest_version": 2
    },
    {
      "dataset_id": 107,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/okx-spot-spot-BTC-USDT-trade-20260901-20260904-d107",
      "manifest_version": 2
    },
    {
      "dataset_id": 109,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/bitget-spot-spot-BTCUSDT-trade-20260901-20260904-d109",
      "manifest_version": 2
    },
    {
      "dataset_id": 111,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/gateio-spot-spot-BTC_USDT-trade-20260901-20261001-d111",
      "manifest_version": 2
    },
    {
      "dataset_id": 113,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/bybit-spot-spot-ETHUSDC-trade-20260901-20260904-d113",
      "manifest_version": 2
    },
    {
      "dataset_id": 115,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/binance-spot-spot-ETHUSDC-trade-20260901-20260904-d115",
      "manifest_version": 2
    },
    {
      "dataset_id": 116,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/bitget-spot-spot-ETHUSDC-trade-20260901-20260904-d116",
      "manifest_version": 2
    },
    {
      "dataset_id": 118,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/binance-future-linear-BTCUSDT_261225-trade-20260901-20260904-d118",
      "manifest_version": 2
    },
    {
      "dataset_id": 119,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/binance-future-inverse-BTCUSD_261225-trade-20260901-20260904-d119",
      "manifest_version": 2
    },
    {
      "dataset_id": 120,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/okx-future-linear-BTC-USD_UM-261225-trade-20260901-20260904-d120",
      "manifest_version": 2
    },
    {
      "dataset_id": 122,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/.work/full-trade-test/datasets/okx-future-inverse-BTC-USD-261225-trade-20260901-20260904-d122",
      "manifest_version": 2
    },
    {
      "dataset_id": 89,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/89",
      "manifest_version": 2
    },
    {
      "dataset_id": 92,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/92",
      "manifest_version": 2
    },
    {
      "dataset_id": 94,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/94",
      "manifest_version": 2
    },
    {
      "dataset_id": 96,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/96",
      "manifest_version": 2
    },
    {
      "dataset_id": 98,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/98",
      "manifest_version": 2
    },
    {
      "dataset_id": 101,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/101",
      "manifest_version": 2
    },
    {
      "dataset_id": 103,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/103",
      "manifest_version": 2
    },
    {
      "dataset_id": 105,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/105",
      "manifest_version": 2
    },
    {
      "dataset_id": 108,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/108",
      "manifest_version": 2
    },
    {
      "dataset_id": 110,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/110",
      "manifest_version": 2
    },
    {
      "dataset_id": 112,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/112",
      "manifest_version": 2
    },
    {
      "dataset_id": 114,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/114",
      "manifest_version": 2
    },
    {
      "dataset_id": 117,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/117",
      "manifest_version": 2
    },
    {
      "dataset_id": 121,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/121",
      "manifest_version": 2
    },
    {
      "dataset_id": 123,
      "dataset_path": "/home/pasha/projects/bybit-history-downloader/data/processed/123",
      "manifest_version": 2
    }
  ],
  "time_range": {
    "start_ns": 1788220800000000000,
    "end_ns": 1788480000000000000
  },
  "events_written": 455688143,
  "trade_events": 50106717,
  "depth_events": 405581426,
  "files_written": 64,
  "start_timestamp_ns": 1788220800000000000,
  "end_timestamp_ns": 1788479999975309000,
  "files": [
    {
      "path": "timeline/partition-000000/part-000000.parquet",
      "size_bytes": 21085639,
      "partition_id": 0,
      "rows": 4839879,
      "start_timestamp_ns": 1788220800000000000,
      "end_timestamp_ns": 1788224849997392000
    },
    {
      "path": "timeline/partition-000001/part-000000.parquet",
      "size_bytes": 24956253,
      "partition_id": 1,
      "rows": 5758887,
      "start_timestamp_ns": 1788224850000000000,
      "end_timestamp_ns": 1788228899974000000
    },
    {
      "path": "timeline/partition-000002/part-000000.parquet",
      "size_bytes": 20178036,
      "partition_id": 2,
      "rows": 4582084,
      "start_timestamp_ns": 1788228900000000000,
      "end_timestamp_ns": 1788232949945000000
    },
    {
      "path": "timeline/partition-000003/part-000000.parquet",
      "size_bytes": 23801647,
      "partition_id": 3,
      "rows": 5530266,
      "start_timestamp_ns": 1788232950000000000,
      "end_timestamp_ns": 1788236999961000000
    },
    {
      "path": "timeline/partition-000004/part-000000.parquet",
      "size_bytes": 21977071,
      "partition_id": 4,
      "rows": 5132630,
      "start_timestamp_ns": 1788237000000000000,
      "end_timestamp_ns": 1788241049955843000
    },
    {
      "path": "timeline/partition-000005/part-000000.parquet",
      "size_bytes": 23767048,
      "partition_id": 5,
      "rows": 5539547,
      "start_timestamp_ns": 1788241050000000000,
      "end_timestamp_ns": 1788245099959000000
    },
    {
      "path": "timeline/partition-000006/part-000000.parquet",
      "size_bytes": 20957621,
      "partition_id": 6,
      "rows": 4740713,
      "start_timestamp_ns": 1788245100000000000,
      "end_timestamp_ns": 1788249149964000000
    },
    {
      "path": "timeline/partition-000007/part-000000.parquet",
      "size_bytes": 36938246,
      "partition_id": 7,
      "rows": 8685560,
      "start_timestamp_ns": 1788249150000000000,
      "end_timestamp_ns": 1788253199961000000
    },
    {
      "path": "timeline/partition-000008/part-000000.parquet",
      "size_bytes": 24835379,
      "partition_id": 8,
      "rows": 5622405,
      "start_timestamp_ns": 1788253200000000000,
      "end_timestamp_ns": 1788257249977000000
    },
    {
      "path": "timeline/partition-000009/part-000000.parquet",
      "size_bytes": 25566636,
      "partition_id": 9,
      "rows": 5820956,
      "start_timestamp_ns": 1788257250000000000,
      "end_timestamp_ns": 1788261299981000000
    },
    {
      "path": "timeline/partition-000010/part-000000.parquet",
      "size_bytes": 24799975,
      "partition_id": 10,
      "rows": 5748590,
      "start_timestamp_ns": 1788261300000000000,
      "end_timestamp_ns": 1788265349946669000
    },
    {
      "path": "timeline/partition-000011/part-000000.parquet",
      "size_bytes": 37509259,
      "partition_id": 11,
      "rows": 9130016,
      "start_timestamp_ns": 1788265350000000000,
      "end_timestamp_ns": 1788269399999000000
    },
    {
      "path": "timeline/partition-000012/part-000000.parquet",
      "size_bytes": 62248669,
      "partition_id": 12,
      "rows": 15513419,
      "start_timestamp_ns": 1788269400000000000,
      "end_timestamp_ns": 1788273449925000000
    },
    {
      "path": "timeline/partition-000013/part-000000.parquet",
      "size_bytes": 38439624,
      "partition_id": 13,
      "rows": 9494971,
      "start_timestamp_ns": 1788273450000000000,
      "end_timestamp_ns": 1788277499999000000
    },
    {
      "path": "timeline/partition-000014/part-000000.parquet",
      "size_bytes": 39764460,
      "partition_id": 14,
      "rows": 9687116,
      "start_timestamp_ns": 1788277500000000000,
      "end_timestamp_ns": 1788281549958000000
    },
    {
      "path": "timeline/partition-000015/part-000000.parquet",
      "size_bytes": 30740308,
      "partition_id": 15,
      "rows": 7271602,
      "start_timestamp_ns": 1788281550000000000,
      "end_timestamp_ns": 1788285599996000000
    },
    {
      "path": "timeline/partition-000016/part-000000.parquet",
      "size_bytes": 52768113,
      "partition_id": 16,
      "rows": 12706271,
      "start_timestamp_ns": 1788285600000000000,
      "end_timestamp_ns": 1788289649958000000
    },
    {
      "path": "timeline/partition-000017/part-000000.parquet",
      "size_bytes": 28680477,
      "partition_id": 17,
      "rows": 6763614,
      "start_timestamp_ns": 1788289650000000000,
      "end_timestamp_ns": 1788293699992000000
    },
    {
      "path": "timeline/partition-000018/part-000000.parquet",
      "size_bytes": 24287916,
      "partition_id": 18,
      "rows": 5640472,
      "start_timestamp_ns": 1788293700000000000,
      "end_timestamp_ns": 1788297749990000000
    },
    {
      "path": "timeline/partition-000019/part-000000.parquet",
      "size_bytes": 21239790,
      "partition_id": 19,
      "rows": 4904413,
      "start_timestamp_ns": 1788297750000000000,
      "end_timestamp_ns": 1788301799996000000
    },
    {
      "path": "timeline/partition-000020/part-000000.parquet",
      "size_bytes": 21072668,
      "partition_id": 20,
      "rows": 4857912,
      "start_timestamp_ns": 1788301800000000000,
      "end_timestamp_ns": 1788305849949000000
    },
    {
      "path": "timeline/partition-000021/part-000000.parquet",
      "size_bytes": 24511351,
      "partition_id": 21,
      "rows": 5662247,
      "start_timestamp_ns": 1788305850000000000,
      "end_timestamp_ns": 1788309899943431000
    },
    {
      "path": "timeline/partition-000022/part-000000.parquet",
      "size_bytes": 30832193,
      "partition_id": 22,
      "rows": 7294082,
      "start_timestamp_ns": 1788309900000000000,
      "end_timestamp_ns": 1788313949961000000
    },
    {
      "path": "timeline/partition-000023/part-000000.parquet",
      "size_bytes": 30883715,
      "partition_id": 23,
      "rows": 7224574,
      "start_timestamp_ns": 1788313950000000000,
      "end_timestamp_ns": 1788317999984000000
    },
    {
      "path": "timeline/partition-000024/part-000000.parquet",
      "size_bytes": 27682935,
      "partition_id": 24,
      "rows": 6461027,
      "start_timestamp_ns": 1788318000000000000,
      "end_timestamp_ns": 1788322049949000000
    },
    {
      "path": "timeline/partition-000025/part-000000.parquet",
      "size_bytes": 19947225,
      "partition_id": 25,
      "rows": 4382942,
      "start_timestamp_ns": 1788322050000000000,
      "end_timestamp_ns": 1788326099929000000
    },
    {
      "path": "timeline/partition-000026/part-000000.parquet",
      "size_bytes": 23618371,
      "partition_id": 26,
      "rows": 5479818,
      "start_timestamp_ns": 1788326100000000000,
      "end_timestamp_ns": 1788330149927000000
    },
    {
      "path": "timeline/partition-000027/part-000000.parquet",
      "size_bytes": 21427877,
      "partition_id": 27,
      "rows": 4946687,
      "start_timestamp_ns": 1788330150000000000,
      "end_timestamp_ns": 1788334199979000000
    },
    {
      "path": "timeline/partition-000028/part-000000.parquet",
      "size_bytes": 23417733,
      "partition_id": 28,
      "rows": 5351144,
      "start_timestamp_ns": 1788334200000000000,
      "end_timestamp_ns": 1788338249996000000
    },
    {
      "path": "timeline/partition-000029/part-000000.parquet",
      "size_bytes": 39073332,
      "partition_id": 29,
      "rows": 9418270,
      "start_timestamp_ns": 1788338250000000000,
      "end_timestamp_ns": 1788342299984419000
    },
    {
      "path": "timeline/partition-000030/part-000000.parquet",
      "size_bytes": 32228834,
      "partition_id": 30,
      "rows": 7652723,
      "start_timestamp_ns": 1788342300000000000,
      "end_timestamp_ns": 1788346349961000000
    },
    {
      "path": "timeline/partition-000031/part-000000.parquet",
      "size_bytes": 33558093,
      "partition_id": 31,
      "rows": 8056900,
      "start_timestamp_ns": 1788346350000000000,
      "end_timestamp_ns": 1788350399981000000
    },
    {
      "path": "timeline/partition-000032/part-000000.parquet",
      "size_bytes": 31957993,
      "partition_id": 32,
      "rows": 7643004,
      "start_timestamp_ns": 1788350400000000000,
      "end_timestamp_ns": 1788354449980298000
    },
    {
      "path": "timeline/partition-000033/part-000000.parquet",
      "size_bytes": 55521393,
      "partition_id": 33,
      "rows": 13846191,
      "start_timestamp_ns": 1788354450000000000,
      "end_timestamp_ns": 1788358499981000000
    },
    {
      "path": "timeline/partition-000034/part-000000.parquet",
      "size_bytes": 48231273,
      "partition_id": 34,
      "rows": 12007979,
      "start_timestamp_ns": 1788358500000000000,
      "end_timestamp_ns": 1788362549961000000
    },
    {
      "path": "timeline/partition-000035/part-000000.parquet",
      "size_bytes": 39589519,
      "partition_id": 35,
      "rows": 9637440,
      "start_timestamp_ns": 1788362550000000000,
      "end_timestamp_ns": 1788366599968000000
    },
    {
      "path": "timeline/partition-000036/part-000000.parquet",
      "size_bytes": 30645441,
      "partition_id": 36,
      "rows": 7222828,
      "start_timestamp_ns": 1788366600000000000,
      "end_timestamp_ns": 1788370649949000000
    },
    {
      "path": "timeline/partition-000037/part-000000.parquet",
      "size_bytes": 25146931,
      "partition_id": 37,
      "rows": 5874371,
      "start_timestamp_ns": 1788370650000000000,
      "end_timestamp_ns": 1788374699994248000
    },
    {
      "path": "timeline/partition-000038/part-000000.parquet",
      "size_bytes": 22913955,
      "partition_id": 38,
      "rows": 5372952,
      "start_timestamp_ns": 1788374700000000000,
      "end_timestamp_ns": 1788378749971000000
    },
    {
      "path": "timeline/partition-000039/part-000000.parquet",
      "size_bytes": 24384405,
      "partition_id": 39,
      "rows": 5686201,
      "start_timestamp_ns": 1788378750000000000,
      "end_timestamp_ns": 1788382799945000000
    },
    {
      "path": "timeline/partition-000040/part-000000.parquet",
      "size_bytes": 18059004,
      "partition_id": 40,
      "rows": 4073819,
      "start_timestamp_ns": 1788382800000000000,
      "end_timestamp_ns": 1788386849931000000
    },
    {
      "path": "timeline/partition-000041/part-000000.parquet",
      "size_bytes": 18567690,
      "partition_id": 41,
      "rows": 4202537,
      "start_timestamp_ns": 1788386850000000000,
      "end_timestamp_ns": 1788390899964000000
    },
    {
      "path": "timeline/partition-000042/part-000000.parquet",
      "size_bytes": 20264544,
      "partition_id": 42,
      "rows": 4558928,
      "start_timestamp_ns": 1788390900000000000,
      "end_timestamp_ns": 1788394949977449000
    },
    {
      "path": "timeline/partition-000043/part-000000.parquet",
      "size_bytes": 28121676,
      "partition_id": 43,
      "rows": 6715241,
      "start_timestamp_ns": 1788394950000000000,
      "end_timestamp_ns": 1788398999959000000
    },
    {
      "path": "timeline/partition-000044/part-000000.parquet",
      "size_bytes": 31656388,
      "partition_id": 44,
      "rows": 7489395,
      "start_timestamp_ns": 1788399000000000000,
      "end_timestamp_ns": 1788403049961000000
    },
    {
      "path": "timeline/partition-000045/part-000000.parquet",
      "size_bytes": 25259056,
      "partition_id": 45,
      "rows": 5839694,
      "start_timestamp_ns": 1788403050000000000,
      "end_timestamp_ns": 1788407099996000000
    },
    {
      "path": "timeline/partition-000046/part-000000.parquet",
      "size_bytes": 18462494,
      "partition_id": 46,
      "rows": 4144045,
      "start_timestamp_ns": 1788407100000000000,
      "end_timestamp_ns": 1788411149956000000
    },
    {
      "path": "timeline/partition-000047/part-000000.parquet",
      "size_bytes": 32924146,
      "partition_id": 47,
      "rows": 7939622,
      "start_timestamp_ns": 1788411150000000000,
      "end_timestamp_ns": 1788415199991300000
    },
    {

In [29]:
import pyarrow as pa

pf = pq.ParquetFile(files[0])

batch = next(pf.iter_batches(batch_size=100))
table = pa.Table.from_batches([batch])

df = pl.from_arrow(table)

df = df.with_columns(
    pl.from_epoch(
        "event_timestamp_ns",
        time_unit="ns",
    ).alias("datetime_utc"),

    pl.when(pl.col("event_kind") == 0)
    .then(pl.lit("TRADE"))
    .otherwise(pl.lit("DEPTH"))
    .alias("event_type"),
)

with pl.Config(
    tbl_cols=-1,
    tbl_width_chars=240,
    fmt_str_lengths=40,
):
    print(df)

shape: (100, 12)
┌─────────────────────┬─────────────┬────────────┬────────────┬─────────┬───────────────┬──────────────────────┬─────────────────────┬────────────────┬──────────────────┬─────────────────────┬────────────┐
│ event_timestamp_ns  ┆ stream_rank ┆ event_kind ┆ dataset_id ┆ task_id ┆ event_ordinal ┆ canonical_row_offset ┆ canonical_row_count ┆ event_boundary ┆ source_operation ┆ datetime_utc        ┆ event_type │
│ ---                 ┆ ---         ┆ ---        ┆ ---        ┆ ---     ┆ ---           ┆ ---                  ┆ ---                 ┆ ---            ┆ ---              ┆ ---                 ┆ ---        │
│ i64                 ┆ u32         ┆ u8         ┆ u64        ┆ u64     ┆ u64           ┆ u64                  ┆ u64                 ┆ u8             ┆ u8               ┆ datetime[ns]        ┆ str        │
╞═════════════════════╪═════════════╪════════════╪════════════╪═════════╪═══════════════╪══════════════════════╪═════════════════════╪════════════════╪══════════════════╪═════════════════════╪════════════╡
│ 1788220800000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 2       ┆ 62633         ┆ 62633                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-01 00:00:00 ┆ TRADE      │
│ 1788220800000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 2       ┆ 62634         ┆ 62634                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-01 00:00:00 ┆ TRADE      │
│ 1788220800000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 2       ┆ 62635         ┆ 62635                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-01 00:00:00 ┆ TRADE      │
│ 1788220800000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 2       ┆ 62636         ┆ 62636                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-01 00:00:00 ┆ TRADE      │
│ 1788220800000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 2       ┆ 62637         ┆ 62637                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-01 00:00:00 ┆ TRADE      │
│ …                   ┆ …           ┆ …          ┆ …          ┆ …       ┆ …             ┆ …                    ┆ …                   ┆ …              ┆ …                ┆ …                   ┆ …          │
│ 1788220800000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 0       ┆ 44104         ┆ 44103                ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-01 00:00:00 ┆ DEPTH      │
│ 1788220800000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 0       ┆ 44105         ┆ 44104                ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-01 00:00:00 ┆ DEPTH      │
│ 1788220800000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 0       ┆ 44106         ┆ 44105                ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-01 00:00:00 ┆ DEPTH      │
│ 1788220800000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 0       ┆ 44107         ┆ 44106                ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-01 00:00:00 ┆ DEPTH      │
│ 1788220800000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 0       ┆ 44108         ┆ 44107                ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-01 00:00:00 ┆ DEPTH      │
└─────────────────────┴─────────────┴────────────┴────────────┴─────────┴───────────────┴──────────────────────┴─────────────────────┴────────────────┴──────────────────┴─────────────────────┴────────────┘

In [30]:
depth_refs = (
    pl.scan_parquet(str(MERGED / "timeline/**/*.parquet"))
    .filter(pl.col("event_kind") == 1)
    .select(
        "event_timestamp_ns",
        "dataset_id",
        "task_id",
        "event_ordinal",
        "canonical_row_offset",
        "canonical_row_count",
        "event_boundary",
        "source_operation",
    )
    .head(100_000)
    .collect()
)

print("DEPTH EVENTS SAMPLED:", len(depth_refs))

print("\nCANONICAL ROW COUNT DISTRIBUTION:")

print(
    depth_refs.select(
        pl.col("canonical_row_count").min().alias("min"),
        pl.col("canonical_row_count").median().alias("median"),
        pl.col("canonical_row_count").mean().alias("mean"),
        pl.col("canonical_row_count").quantile(0.95).alias("p95"),
        pl.col("canonical_row_count").quantile(0.99).alias("p99"),
        pl.col("canonical_row_count").max().alias("max"),
    )
)

print("\nEVENTS BY ROW COUNT:")

print(
    depth_refs.select(
        (pl.col("canonical_row_count") == 0).sum().alias("zero"),
        (pl.col("canonical_row_count") == 1).sum().alias("one"),
        (pl.col("canonical_row_count") > 1).sum().alias("multiple"),
        (pl.col("canonical_row_count") > 100).sum().alias("over_100"),
        (pl.col("canonical_row_count") > 1000).sum().alias("over_1000"),
    )
)

print("\nLARGEST DEPTH EVENTS:")

with pl.Config(tbl_cols=-1, tbl_width_chars=220):
    print(
        depth_refs.sort(
            "canonical_row_count",
            descending=True,
        ).head(15)
    )

DEPTH EVENTS SAMPLED: 100000

CANONICAL ROW COUNT DISTRIBUTION:
shape: (1, 6)
┌─────┬────────┬────────┬─────┬──────┬───────┐
│ min ┆ median ┆ mean   ┆ p95 ┆ p99  ┆ max   │
│ --- ┆ ---    ┆ ---    ┆ --- ┆ ---  ┆ ---   │
│ u64 ┆ f64    ┆ f64    ┆ f64 ┆ f64  ┆ u64   │
╞═════╪════════╪════════╪═════╪══════╪═══════╡
│ 1   ┆ 1.0    ┆ 3.2286 ┆ 1.0 ┆ 27.0 ┆ 53923 │
└─────┴────────┴────────┴─────┴──────┴───────┘

EVENTS BY ROW COUNT:
shape: (1, 5)
┌──────┬───────┬──────────┬──────────┬───────────┐
│ zero ┆ one   ┆ multiple ┆ over_100 ┆ over_1000 │
│ ---  ┆ ---   ┆ ---      ┆ ---      ┆ ---       │
│ u32  ┆ u32   ┆ u32      ┆ u32      ┆ u32       │
╞══════╪═══════╪══════════╪══════════╪═══════════╡
│ 0    ┆ 96896 ┆ 3104     ┆ 176      ┆ 6         │
└──────┴───────┴──────────┴──────────┴───────────┘

LARGEST DEPTH EVENTS:
shape: (15, 8)
┌─────────────────────┬────────────┬─────────┬───────────────┬──────────────────────┬─────────────────────┬────────────────┬──────────────────┐
│ event_timestamp_ns  ┆ dataset_id ┆ task_id ┆ event_ordinal ┆ canonical_row_offset ┆ canonical_row_count ┆ event_boundary ┆ source_operation │
│ ---                 ┆ ---        ┆ ---     ┆ ---           ┆ ---                  ┆ ---                 ┆ ---            ┆ ---              │
│ i64                 ┆ u64        ┆ u64     ┆ u64           ┆ u64                  ┆ u64                 ┆ u8             ┆ u8               │
╞═════════════════════╪════════════╪═════════╪═══════════════╪══════════════════════╪═════════════════════╪════════════════╪══════════════════╡
│ 1788220800000000000 ┆ 112        ┆ 0       ┆ 53923         ┆ 0                    ┆ 53923               ┆ 1              ┆ 0                │
│ 1788220800000000000 ┆ 96         ┆ 0       ┆ 44061         ┆ 0                    ┆ 44061               ┆ 1              ┆ 0                │
│ 1788220800001000000 ┆ 101        ┆ 0       ┆ 1             ┆ 0                    ┆ 10000               ┆ 1              ┆ 0                │
│ 1788220800006000000 ┆ 92         ┆ 0       ┆ 1             ┆ 0                    ┆ 10000               ┆ 1              ┆ 0                │
│ 1788220800006000000 ┆ 108        ┆ 0       ┆ 1             ┆ 0                    ┆ 10000               ┆ 1              ┆ 0                │
│ …                   ┆ …          ┆ …       ┆ …             ┆ …                    ┆ …                   ┆ …              ┆ …                │
│ 1788220865000000000 ┆ 94         ┆ 0       ┆ 1444          ┆ 1152750              ┆ 756                 ┆ 0              ┆ 0                │
│ 1788220805000000000 ┆ 94         ┆ 0       ┆ 1441          ┆ 1150629              ┆ 752                 ┆ 0              ┆ 0                │
│ 1788220845000000000 ┆ 94         ┆ 0       ┆ 1443          ┆ 1152036              ┆ 714                 ┆ 0              ┆ 0                │
│ 1788220829006000000 ┆ 92         ┆ 0       ┆ 30            ┆ 16538                ┆ 677                 ┆ 0              ┆ 1                │
│ 1788220825000000000 ┆ 94         ┆ 0       ┆ 1442          ┆ 1151381              ┆ 655                 ┆ 0              ┆ 0                │
└─────────────────────┴────────────┴─────────┴───────────────┴──────────────────────┴─────────────────────┴────────────────┴──────────────────┘

In [31]:
print("EVENT BOUNDARIES:")

print(
    depth_refs.group_by("event_boundary")
    .agg(
        pl.len().alias("events"),
        pl.col("canonical_row_count").sum().alias("canonical_levels"),
    )
    .sort("event_boundary")
)

print("\nSOURCE OPERATIONS:")

print(
    depth_refs.group_by("source_operation")
    .agg(
        pl.len().alias("events"),
        pl.col("canonical_row_count").sum().alias("canonical_levels"),
    )
    .sort("source_operation")
)

print("\nBOUNDARY × OPERATION:")

print(
    depth_refs.group_by(
        "event_boundary",
        "source_operation",
    )
    .agg(
        pl.len().alias("events"),
        pl.col("canonical_row_count").sum().alias("canonical_levels"),
    )
    .sort("event_boundary", "source_operation")
)

EVENT BOUNDARIES:
shape: (2, 3)
┌────────────────┬────────┬──────────────────┐
│ event_boundary ┆ events ┆ canonical_levels │
│ ---            ┆ ---    ┆ ---              │
│ u8             ┆ u32    ┆ u64              │
╞════════════════╪════════╪══════════════════╡
│ 0              ┆ 99988  ┆ 190961           │
│ 1              ┆ 12     ┆ 131899           │
└────────────────┴────────┴──────────────────┘

SOURCE OPERATIONS:
shape: (3, 3)
┌──────────────────┬────────┬──────────────────┐
│ source_operation ┆ events ┆ canonical_levels │
│ ---              ┆ ---    ┆ ---              │
│ u8               ┆ u32    ┆ u64              │
╞══════════════════╪════════╪══════════════════╡
│ 0                ┆ 24     ┆ 136413           │
│ 1                ┆ 3130   ┆ 89601            │
│ 2                ┆ 96846  ┆ 96846            │
└──────────────────┴────────┴──────────────────┘

BOUNDARY × OPERATION:
shape: (4, 4)
┌────────────────┬──────────────────┬────────┬──────────────────┐
│ event_boundary ┆ source_operation ┆ events ┆ canonical_levels │
│ ---            ┆ ---              ┆ ---    ┆ ---              │
│ u8             ┆ u8               ┆ u32    ┆ u64              │
╞════════════════╪══════════════════╪════════╪══════════════════╡
│ 0              ┆ 0                ┆ 12     ┆ 4514             │
│ 0              ┆ 1                ┆ 3130   ┆ 89601            │
│ 0              ┆ 2                ┆ 96846  ┆ 96846            │
│ 1              ┆ 0                ┆ 12     ┆ 131899           │
└────────────────┴──────────────────┴────────┴──────────────────┘

In [32]:
import polars as pl

COMBINED = ROOT / "data/merged/920003"

combined = pl.scan_parquet(
    str(COMBINED / "timeline/**/*.parquet")
)

print("COMBINED DATASET — EVENT DISTRIBUTION")

display(
    combined
    .group_by("event_kind")
    .agg(pl.len().alias("events"))
    .sort("event_kind")
    .collect()
)

print("\nSTREAM DISTRIBUTION")

display(
    combined
    .group_by("stream_rank", "event_kind")
    .agg(pl.len().alias("events"))
    .sort("stream_rank", "event_kind")
    .collect()
)

COMBINED DATASET — EVENT DISTRIBUTION

shape: (2, 2)
┌────────────┬───────────┐
│ event_kind ┆ events    │
│ ---        ┆ ---       │
│ u8         ┆ u32       │
╞════════════╪═══════════╡
│ 0          ┆ 50106717  │
│ 1          ┆ 405581426 │
└────────────┴───────────┘

STREAM DISTRIBUTION

shape: (36, 3)
┌─────────────┬────────────┬──────────┐
│ stream_rank ┆ event_kind ┆ events   │
│ ---         ┆ ---        ┆ ---      │
│ u32         ┆ u8         ┆ u32      │
╞═════════════╪════════════╪══════════╡
│ 0           ┆ 0          ┆ 6593458  │
│ 1           ┆ 0          ┆ 11920180 │
│ 2           ┆ 0          ┆ 7680704  │
│ 3           ┆ 0          ┆ 3037806  │
│ 4           ┆ 0          ┆ 3161178  │
│ …           ┆ …          ┆ …        │
│ 31          ┆ 1          ┆ 64869304 │
│ 32          ┆ 1          ┆ 1333233  │
│ 33          ┆ 1          ┆ 11446    │
│ 34          ┆ 1          ┆ 75422    │
│ 35          ┆ 1          ┆ 217745   │
└─────────────┴────────────┴──────────┘

In [33]:
import polars as pl

COMBINED = ROOT / "data/merged/920003"

combined = pl.scan_parquet(
    str(COMBINED / "timeline/**/*.parquet")
)

print("COMBINED DATASET — EVENT DISTRIBUTION")

display(
    combined
    .group_by("event_kind")
    .agg(pl.len().alias("events"))
    .sort("event_kind")
    .collect()
)

print("\nSTREAM DISTRIBUTION")

display(
    combined
    .group_by("stream_rank", "event_kind")
    .agg(pl.len().alias("events"))
    .sort("stream_rank", "event_kind")
    .collect()
)

COMBINED DATASET — EVENT DISTRIBUTION

shape: (2, 2)
┌────────────┬───────────┐
│ event_kind ┆ events    │
│ ---        ┆ ---       │
│ u8         ┆ u32       │
╞════════════╪═══════════╡
│ 0          ┆ 50106717  │
│ 1          ┆ 405581426 │
└────────────┴───────────┘

STREAM DISTRIBUTION

shape: (36, 3)
┌─────────────┬────────────┬──────────┐
│ stream_rank ┆ event_kind ┆ events   │
│ ---         ┆ ---        ┆ ---      │
│ u32         ┆ u8         ┆ u32      │
╞═════════════╪════════════╪══════════╡
│ 0           ┆ 0          ┆ 6593458  │
│ 1           ┆ 0          ┆ 11920180 │
│ 2           ┆ 0          ┆ 7680704  │
│ 3           ┆ 0          ┆ 3037806  │
│ 4           ┆ 0          ┆ 3161178  │
│ …           ┆ …          ┆ …        │
│ 31          ┆ 1          ┆ 64869304 │
│ 32          ┆ 1          ┆ 1333233  │
│ 33          ┆ 1          ┆ 11446    │
│ 34          ┆ 1          ┆ 75422    │
│ 35          ┆ 1          ┆ 217745   │
└─────────────┴────────────┴──────────┘

In [34]:
import pyarrow.parquet as pq
import pyarrow as pa

files = sorted(
    COMBINED.glob("timeline/**/*.parquet")
)

# Select a partition near the middle of the dataset
file = files[len(files) // 2]

print("FILE:", file.relative_to(COMBINED))

pf = pq.ParquetFile(file)

batch = next(pf.iter_batches(batch_size=1000))
table = pa.Table.from_batches([batch])

df = pl.from_arrow(table)

df = df.with_columns(
    pl.from_epoch(
        "event_timestamp_ns",
        time_unit="ns",
    ).alias("datetime_utc"),

    pl.when(pl.col("event_kind") == 0)
    .then(pl.lit("TRADE"))
    .otherwise(pl.lit("DEPTH"))
    .alias("event_type"),
)

with pl.Config(
    tbl_cols=-1,
    tbl_width_chars=240,
    fmt_str_lengths=40,
):
    print(df.head(50))

FILE: timeline/partition-000032/part-000000.parquet
shape: (50, 12)
┌─────────────────────┬─────────────┬────────────┬────────────┬─────────┬───────────────┬──────────────────────┬─────────────────────┬────────────────┬──────────────────┬─────────────────────┬────────────┐
│ event_timestamp_ns  ┆ stream_rank ┆ event_kind ┆ dataset_id ┆ task_id ┆ event_ordinal ┆ canonical_row_offset ┆ canonical_row_count ┆ event_boundary ┆ source_operation ┆ datetime_utc        ┆ event_type │
│ ---                 ┆ ---         ┆ ---        ┆ ---        ┆ ---     ┆ ---           ┆ ---                  ┆ ---                 ┆ ---            ┆ ---              ┆ ---                 ┆ ---        │
│ i64                 ┆ u32         ┆ u8         ┆ u64        ┆ u64     ┆ u64           ┆ u64                  ┆ u64                 ┆ u8             ┆ u8               ┆ datetime[ns]        ┆ str        │
╞═════════════════════╪═════════════╪════════════╪════════════╪═════════╪═══════════════╪══════════════════════╪═════════════════════╪════════════════╪══════════════════╪═════════════════════╪════════════╡
│ 1788350400000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 18      ┆ 77356         ┆ 77356                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-02 12:00:00 ┆ TRADE      │
│ 1788350400000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 18      ┆ 77357         ┆ 77357                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-02 12:00:00 ┆ TRADE      │
│ 1788350400000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 18      ┆ 77358         ┆ 77358                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-02 12:00:00 ┆ TRADE      │
│ 1788350400000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 18      ┆ 77359         ┆ 77359                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-02 12:00:00 ┆ TRADE      │
│ 1788350400000000000 ┆ 3           ┆ 0          ┆ 93         ┆ 18      ┆ 77360         ┆ 77360                ┆ 1                   ┆ null           ┆ null             ┆ 2026-09-02 12:00:00 ┆ TRADE      │
│ …                   ┆ …           ┆ …          ┆ …          ┆ …       ┆ …             ┆ …                    ┆ …                   ┆ …              ┆ …                ┆ …                   ┆ …          │
│ 1788350400000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 35      ┆ 4839157       ┆ 4839156              ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-02 12:00:00 ┆ DEPTH      │
│ 1788350400000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 35      ┆ 4839158       ┆ 4839157              ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-02 12:00:00 ┆ DEPTH      │
│ 1788350400000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 35      ┆ 4839159       ┆ 4839158              ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-02 12:00:00 ┆ DEPTH      │
│ 1788350400000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 35      ┆ 4839160       ┆ 4839159              ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-02 12:00:00 ┆ DEPTH      │
│ 1788350400000000000 ┆ 24          ┆ 1          ┆ 96         ┆ 35      ┆ 4839161       ┆ 4839160              ┆ 1                   ┆ 0              ┆ 2                ┆ 2026-09-02 12:00:00 ┆ DEPTH      │
└─────────────────────┴─────────────┴────────────┴────────────┴─────────┴───────────────┴──────────────────────┴─────────────────────┴────────────────┴──────────────────┴─────────────────────┴────────────┘

In [35]:
transitions = (
    df
    .with_columns(
        pl.col("event_type")
        .shift(1)
        .alias("previous_type")
    )
    .filter(
        pl.col("event_type") != pl.col("previous_type")
    )
    .select(
        "datetime_utc",
        "event_type",
        "stream_rank",
        "dataset_id",
        "task_id",
        "event_ordinal",
        "canonical_row_count",
    )
)

print("TRADE / DEPTH TRANSITIONS")

with pl.Config(
    tbl_cols=-1,
    tbl_width_chars=220,
):
    print(transitions.head(30))

TRADE / DEPTH TRANSITIONS
shape: (30, 7)
┌────────────────────────────┬────────────┬─────────────┬────────────┬─────────┬───────────────┬─────────────────────┐
│ datetime_utc               ┆ event_type ┆ stream_rank ┆ dataset_id ┆ task_id ┆ event_ordinal ┆ canonical_row_count │
│ ---                        ┆ ---        ┆ ---         ┆ ---        ┆ ---     ┆ ---           ┆ ---                 │
│ datetime[ns]               ┆ str        ┆ u32         ┆ u64        ┆ u64     ┆ u64           ┆ u64                 │
╞════════════════════════════╪════════════╪═════════════╪════════════╪═════════╪═══════════════╪═════════════════════╡
│ 2026-09-02 12:00:00        ┆ DEPTH      ┆ 24          ┆ 96         ┆ 35      ┆ 4839148       ┆ 1                   │
│ 2026-09-02 12:00:00.012700 ┆ TRADE      ┆ 0           ┆ 88         ┆ 1       ┆ 875894        ┆ 1                   │
│ 2026-09-02 12:00:00.027    ┆ DEPTH      ┆ 21          ┆ 89         ┆ 1       ┆ 431918        ┆ 51                  │
│ 2026-09-02 12:00:00.057    ┆ TRADE      ┆ 1           ┆ 90         ┆ 1       ┆ 1628759       ┆ 1                   │
│ 2026-09-02 12:00:00.061    ┆ DEPTH      ┆ 25          ┆ 98         ┆ 1       ┆ 423510        ┆ 3                   │
│ …                          ┆ …          ┆ …           ┆ …          ┆ …       ┆ …             ┆ …                   │
│ 2026-09-02 12:00:00.421100 ┆ TRADE      ┆ 0           ┆ 88         ┆ 1       ┆ 875916        ┆ 1                   │
│ 2026-09-02 12:00:00.427    ┆ DEPTH      ┆ 21          ┆ 89         ┆ 1       ┆ 431922        ┆ 87                  │
│ 2026-09-02 12:00:00.427700 ┆ TRADE      ┆ 0           ┆ 88         ┆ 1       ┆ 875947        ┆ 1                   │
│ 2026-09-02 12:00:00.430    ┆ DEPTH      ┆ 32          ┆ 114        ┆ 1       ┆ 216916        ┆ 16                  │
│ 2026-09-02 12:00:00.457    ┆ TRADE      ┆ 1           ┆ 90         ┆ 1       ┆ 1628767       ┆ 1                   │
└────────────────────────────┴────────────┴─────────────┴────────────┴─────────┴───────────────┴─────────────────────┘